/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: {
          DEFAULT: 'hsl(var(--background))',
          first: 'hsl(var(--background-first))',
          second: 'hsl(var(--background-second))',
          third: 'hsl(var(--background-third))',
        },
        foreground: 'hsl(var(--foreground))',
        btn: {
          DEFAULT: 'hsl(var(--btn))',
          primary: 'hsl(var(--btn-primary))',
          'primary-hover': 'hsl(var(--btn-primary-hover))',
          secondary: 'hsl(var(--btn-secondary))',
          'secondary-hover': 'hsl(var(--btn-secondary-hover))',
        },
        'green-vivid': {
          DEFAULT: 'hsl(var(--green-vivid))',
          100: 'hsl(var(--green-vivid-100))',
          200: 'hsl(var(--green-vivid-200))',
          300: 'hsl(var(--green-vivid-300))',
          400: 'hsl(var(--green-vivid-400))',
          500: 'hsl(var(--green-vivid-500))',
          600: 'hsl(var(--green-vivid-600))',
          700: 'hsl(var(--green-vivid-700))',
          800: 'hsl(var(--green-vivid-800))',
          900: 'hsl(var(--green-vivid-900))',
        },
        'yellow-vivid': {
          DEFAULT: 'hsl(var(--yellow-vivid))',
          100: 'hsl(var(--yellow-vivid-100))',
          200: 'hsl(var(--yellow-vivid-200))',
          300: 'hsl(var(--yellow-vivid-300))',
          400: 'hsl(var(--yellow-vivid-400))',
          500: 'hsl(var(--yellow-vivid-500))',
          600: 'hsl(var(--yellow-vivid-600))',
          700: 'hsl(var(--yellow-vivid-700))',
          800: 'hsl(var(--yellow-vivid-800))',
          900: 'hsl(var(--yellow-vivid-900))',
        },
        'red-vivid': {
          DEFAULT: 'hsl(var(--red-vivid))',
          100: 'hsl(var(--red-vivid-100))',
          200: 'hsl(var(--red-vivid-200))',
          300: 'hsl(var(--red-vivid-300))',
          400: 'hsl(var(--red-vivid-400))',
          500: 'hsl(var(--red-vivid-500))',
          600: 'hsl(var(--red-vivid-600))',
          700: 'hsl(var(--red-vivid-700))',
          800: 'hsl(var(--red-vivid-800))',
          900: 'hsl(var(--red-vivid-900))',
        },
        'pink-vivid': {
          DEFAULT: 'hsl(var(--pink-vivid))',
          100: 'hsl(var(--pink-vivid-100))',
          200: 'hsl(var(--pink-vivid-200))',
          300: 'hsl(var(--pink-vivid-300))',
          400: 'hsl(var(--pink-vivid-400))',
          500: 'hsl(var(--pink-vivid-500))',
          600: 'hsl(var(--pink-vivid-600))',
          700: 'hsl(var(--pink-vivid-700))',
          800: 'hsl(var(--pink-vivid-800))',
          900: 'hsl(var(--pink-vivid-900))',
        },
        'cyan-vivid': {
          DEFAULT: 'hsl(var(--cyan-vivid))',
          100: 'hsl(var(--cyan-vivid-100))',
          200: 'hsl(var(--cyan-vivid-200))',
          300: 'hsl(var(--cyan-vivid-300))',
          400: 'hsl(var(--cyan-vivid-400))',
          500: 'hsl(var(--cyan-vivid-500))',
          600: 'hsl(var(--cyan-vivid-600))',
          700: 'hsl(var(--cyan-vivid-700))',
          800: 'hsl(var(--cyan-vivid-800))',
          900: 'hsl(var(--cyan-vivid-900))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      screens: {
        break3: '300px',
        break4: '400px',
        break5: '500px',
        break6: '600px',
        break7: '700px',
        break8: '800px',
        break9: '900px',
        break10: '1000px',
        break11: '1100px',
        break12: '1200px',
        break13: '1300px',
        break14: '1400px',
        break15: '1500px',
        break16: '1600px',
        break17: '1700px',
        break18: '1800px',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
